#!/usr/bin/env bash
# ── a2a-gateway developer install script ─────────────────────────────────────
#
# Sets up a local A2A gateway on the developer's machine.
# Requires: Docker, Docker Compose, git
#
# Usage:
#   curl -sf https://agents.cubic.build/install.sh | bash
#   # or locally:
#   ./install.sh
#
# What it does:
#   1. Clones or updates the Tools-A2A repo
#   2. Generates secrets (.env)
#   3. Starts the dev-compose stack (gateway + postgres)
#   4. Verifies the gateway is healthy
#   5. Prints next steps (peer with NAS, run agents)

set -euo pipefail

REPO_URL="https://github.com/cubic-build/tools-a2a"  # update with your actual repo
INSTALL_DIR="${A2A_HOME:-$HOME/.a2a}"

echo "╔══════════════════════════════════════════╗"
echo "║  A2A Gateway — Developer Install         ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Prerequisites ──────────────────────────────────────────────────────────────

check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        echo "error: $1 is required but not installed."
        echo "  install: $2"
        exit 1
    fi
}

check_cmd docker "https://docs.docker.com/get-docker/"
check_cmd git    "brew install git (macOS) or apt install git (Linux)"

# Check Docker daemon is running
if ! docker ps &>/dev/null; then
    echo "error: Docker daemon is not running."
    echo "  Start Docker Desktop (macOS/Windows) or: sudo systemctl start docker (Linux)"
    exit 1
fi

# Check docker compose (v2)
if ! docker compose version &>/dev/null; then
    echo "error: docker compose v2 is required."
    echo "  Docker Desktop includes it. For Linux: https://docs.docker.com/compose/install/"
    exit 1
fi

echo "✓ prerequisites: docker, docker compose, git"

# ── Clone or update ────────────────────────────────────────────────────────────

if [ -d "$INSTALL_DIR" ] && [ -d "$INSTALL_DIR/.git" ]; then
    echo "→ updating existing install at $INSTALL_DIR"
    cd "$INSTALL_DIR"
    if ! git pull --ff-only; then
        echo "warning: git pull failed — using existing version"
    fi
else
    echo "→ cloning to $INSTALL_DIR"
    git clone "$REPO_URL" "$INSTALL_DIR" 2>/dev/null || {
        echo "note: remote clone failed — assuming local install"
        mkdir -p "$INSTALL_DIR"
        if [ -f "dev-compose.yml" ]; then
            cp -r . "$INSTALL_DIR/"
        else
            echo "error: run this script from the Tools-A2A directory, or set REPO_URL"
            exit 1
        fi
    }
fi

cd "$INSTALL_DIR"

# ── Generate .env if missing ──────────────────────────────────────────────────

if [ ! -f .env ]; then
    echo "→ generating .env with random secrets"
    PG_PASS=$(openssl rand -hex 16)
    JWT_SECRET=$(openssl rand -hex 32)
    # Restrict permissions BEFORE writing secrets
    (umask 077; cat > .env <<EOF
# Generated by install.sh — $(date -Iseconds)
POSTGRES_PASSWORD=${PG_PASS}
A2A_JWT_SECRET=${JWT_SECRET}
# Set to your NAS IP for cross-gateway sync:
# NATS_URL=nats://192.168.1.67:4222
EOF
    )
    chmod 600 .env
    echo "✓ .env created (secrets auto-generated, chmod 600)"
else
    echo "✓ .env already exists"
fi

# ── Set gateway name ──────────────────────────────────────────────────────────

HOSTNAME_SHORT=$(hostname -s 2>/dev/null || echo "dev")
USER_NAME=$(whoami 2>/dev/null || echo "user")
GW_NAME="${USER_NAME}-${HOSTNAME_SHORT}"
if grep -q 'name.*=.*"dev-local"' dev-gateway.toml 2>/dev/null; then
    # Use perl for cross-platform compatibility (works on macOS + Linux)
    perl -pi -e "s/\"dev-local\"/\"${GW_NAME}\"/" dev-gateway.toml 2>/dev/null || true
    echo "✓ gateway name set to '${GW_NAME}'"
fi

# ── Start the stack ───────────────────────────────────────────────────────────

echo "→ starting gateway + postgres..."
if ! docker compose -f dev-compose.yml up -d --build 2>&1 | tail -10; then
    echo "error: docker compose failed — check logs:"
    echo "  docker compose -f dev-compose.yml logs"
    exit 1
fi

# Wait for health
echo "→ waiting for gateway to be healthy..."
for i in $(seq 1 30); do
    if curl -sf http://localhost:7242/health &>/dev/null; then
        echo "✓ gateway is healthy"
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "✗ gateway did not become healthy in 30s"
        echo "  check logs: docker compose -f dev-compose.yml logs gateway"
        exit 1
    fi
    sleep 1
done

# ── Print status ──────────────────────────────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════"
echo " A2A Gateway running!"
echo "═══════════════════════════════════════════"
echo ""
echo " Health:     http://localhost:7242/health"
echo " Dashboard:  http://localhost:7243/"
echo " gRPC:       localhost:7240 (agents)"
echo " Peer gRPC:  localhost:7241"
echo ""
echo " ── Next steps ──"
echo ""
echo " 1. Install the CLI:"
echo "    cargo install --path crates/a2a-cli"
echo ""
echo " 2. Peer with a hub gateway (one time):"
echo "    a2a peers add --name hub --endpoint http://<nas-ip>:7241"
echo ""
echo " 3. Join a group (get token from admin):"
echo "    a2a groups join http://<nas-ip>:7241 <invite-token>"
echo ""
echo " 4. Create a local project:"
echo "    a2a projects add my-app --repo https://github.com/you/my-app"
echo ""
echo " 5. Run an agent:"
echo "    cargo run -p orchestrator"
echo ""
echo " Logs: docker compose -f dev-compose.yml logs -f gateway"
echo ""
